--- 
abstract: DateTime Extension for Traditional Japanese Calendars
author: Copyright (c) 2004-2007 Daisuke Maki <daisuke@endeworks.jp<gt>
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: DateTime-Calendar-Japanese
no_index: 
  directory: 
    - inc
    - t
requires: 
  DateTime: 0
  DateTime::Calendar::Chinese: 0
  DateTime::Calendar::Japanese::Era: 0
  DateTime::Event::Sunrise: 0
  DateTime::Util::Calc: 0
  Params::Validate: 0
version: 0.06001
